### PR TITLE
Fix bugs in textMapPropagator.Extract

### LINKED ISSUE #118: Span extraction fails for valid carriers and succeeds for invalid carriers
There is currently a bug in the `(p *textMapPropagator) Extract` function in `propagation_ot.go`.

The extractor defines the minimum number of required fields that are set to be 3, but carriers only need a trace ID and span ID to be valid (and these values also MUST be present per the [HTTP encodings spec in openzipkin/b3-propagation](https://github.com/openzipkin/b3-propagation/blob/master/README.md#http-encodings), which states that `TraceId` and `SpanId` are required). Thus, the current code improperly rejects carriers that have only these values set (this is the same issue as #106).

The current logic also naively increments the "required field" count on any parsed field -- thus, a carrier that has any 3 fields defined on it is considered valid even when it should not be (for example, a carrier with a parent span ID, "sampled" and "flags" is considered valid because it has 3 fields defined, even though trace ID and span ID are required and not defined).

The extraction code should be updated to require that trace ID and span ID be defined and to allow extraction to succeed for carriers with only those values defined.

The [implementation in `openzipkin/zipkin-go`](https://github.com/openzipkin/zipkin-go/blob/master/propagation/b3/spancontext.go) properly handles both of these cases.

### PR DESCRIPTION
**Pull request by nmiyake**
* Fail if a required field (TraceID or SpanID) is not set
* Support carriers that only specify TraceID and SpanID

Fixes #118

### CODE REVIEW

File: propagation_ot.go [hunk 1]
```diff
@@ -85,18 +83,24 @@ func (p *textMapPropagator) Extract(
 		err          error
 	)
 	decodedBaggage := make(map[string]string)
+
+	var traceIDFound, spanIDFound bool
```
Comment (nmiyake) [inline propagation_ot.go]: Used this approach rather than a counter because it is more robust.

Because the case normalization happens inside the `ForeachKey` function, in the previous code, if the carrier stored multiple keys in different cases (for example, `X-B3-TraceId` and `X-B3-Traceid`), then the counter would get incremented twice even though only one field was actually set.

**Comment by basvanbeek** [comment]
Thanks for the contribution. Unfortunately this extraction logic is also flawed. B3 specs allow for Debug or Sampled flags to be set without the traceID and spanID present.

If you want to fix this properly you can take a look at the native zipkin-go implementation:

https://github.com/openzipkin/zipkin-go/blob/master/propagation/b3/spancontext.go

**Comment by nmiyake** [comment]
@basvanbeek I don't think what you in "B3 specs allow for Debug or Sampled flags to be set without the traceID and spanID present" is correct -- the `b3-propagation` spec that you linked clearly states that `TraceId` and `SpanId` are required, and the `zipkin-go` implementation you linked fails if only `Debug` and/or `Sampled` is set:

The line at https://github.com/openzipkin/zipkin-go/blob/master/propagation/b3/spancontext.go#L61 returns `ErrInvalidScope` if `requiredCount != 0 && requiredCount != 2`, and `requiredCount` is only incremented for `TraceId` (https://github.com/openzipkin/zipkin-go/blob/master/propagation/b3/spancontext.go#L46) and `spanId` (https://github.com/openzipkin/zipkin-go/blob/master/propagation/b3/spancontext.go#L53). My PR matches this behavior.

**Comment by nmiyake** [comment]
Sorry, my previous comment was incorrect -- I see that `requiredCount == 0` is allowed by that logic.

I'll update my PR to match behavior.

**Comment by nmiyake** [comment]
@basvanbeek after looking into this, I think that further discussion may be warranted for how to handle span extraction.

As you mentioned, `zipkin-go` has the behavior that span extraction will always succeed -- if no headers are defined, an empty span is returned, and if only optional headers are defined (for example, just sampling is specified), it will extract a span with just those fields specified.

`zipkin-go` defines its own `SpanOption` type, and its `Parent` implementation is such that, if it is provided with a "partial" span, it will only apply the portions that are set. For example, if you specify a parent span context that only has the "sampling" field defined, it will use the field, but because the "parent" span doesn't have a trace ID specified, it will generate a new trace ID and span ID for the context.

Historically, `zipkin-go-opentracing` has taken a different approach -- it uses the errors and interfaces defined in `github.com/opentracing/opentracing-go`.

In particular, in the past, the API was such that, if a span source (such as a header) did not contain enough information to create a valid span, it would return a `nil` context and an `opentracing.ErrSpanContextNotFound` error:

```
// ErrSpanContextNotFound occurs when the `carrier` passed to
// Tracer.Extract() is valid and uncorrupted but has insufficient
// information to extract a SpanContext.
ErrSpanContextNotFound = errors.New("opentracing: SpanContext not found in Extract carrier")
```

Additionally, span options used `opentracing.StartSpanOption`, and parent contexts were set using `opentracing.ChildOf`. The implementation was such that passing a `nil` parent context to this factory function would result in no parent information being set.

Given all of this, I think there are 2 main approaches:

(1) Fix current implementation with minimal API change
In this approach, the current package would maintain its behavior that, if required fields are not set, a `nil` context and error are returned. The code would just be fixed to assert that only `TraceId` and `SpanId` are required (current PR).

(2) Change behavior to allow for partial context extraction and application
In this approach, `Extract` would always return a context -- any fields specified in the carrier would be set on the context, and any not set would not. This means that the extraction would never fail with an `ErrSpanContextNotFound` error -- a context would always be returned unless a field is actually corrupted.

This would require updating the logic in [tracer.go](https://github.com/openzipkin-contrib/zipkin-go-opentracing/blob/master/tracer.go#L310) to handle the `opentracing.ChildOfRef` case in which certain fields are not set -- for example, if the parent context did not have a trace ID set, this code would need to generate a new one and mark the span as a root span.

In my opinion, approach (1) (which is implemented in the current PR) is the more conservative approach and is more appealing to me -- it will correct the current behavior that is objectively wrong/not compliant with the spec without modifying the over-all semantics of the behavior. It also does not preclude implementing option (2) as a more major change at a later time.

If you think option (2) is the correct approach I'm happy to implement it, but wanted to have this discussion first before doing so since that is a larger change that would have a larger impact on the API and could impact logic implemented by current clients of this library.

**Comment by basvanbeek** [comment]
So there are two items to untangle here... one is implementation concern about SpanContext. The other is what is accepted B3 behavior.

The proper solution is that OpenTracing is just an API and has no say and should have no say in what is allowed SpanContext behavior. That is up to the implementation (ecosystem) used. In this case Zipkin B3 is leading. To put it blunty opentracing.ErrSpanContextNotFound is an error to help aide in logic if so desired by an implementor but could be completely ignored by an implementation if not applicable in the way stuff is done.

Most Zipkin libraries allow for Sampled/Debug being set without tracing identifiers Trace id/Span id. For correct interoperability with the entire Zipkin ecosystem this would be preferred to be supported. In case trace identifiers are set it does need to be complete (so at least both TraceID/SpanID and optionally ParentSpanID).

About existing consumers... if it breaks behavior to be Zipkin ecosystem compliant than so be it. We have so much more to guard then just the OpenTracing Go implementation that the choice is easily made.

**Comment by nmiyake** [comment]
OK no problem that works for me — will update PR accordingly.

**Comment by nmiyake** [comment]
Updated PR to address feedback. Also includes the change in #122 to make the Travis build run properly.

**Comment by basvanbeek** [comment]
thanks @nmiyake for the contribution!
